### Login User
POST http://localhost:8000/auth/login/
Content-Type: application/json

{
  "username": "abbas",
  "password": "hsen",
  "company": "default"
}

### Login User 2
POST http://localhost:8000/auth/login/
Content-Type: application/json

{
  "username": "abbas",
  "password": "abbas",
  "company": "company1"
}

### Company
GET http://localhost:8000/auth/companies/abbas
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoxLCJsYXN0X2xvZ2luIjpudWxsLCJpc19zdXBlcnVzZXIiOnRydWUsInVzZXJuYW1lIjoiYWJiYXMiLCJmaXJzdF9uYW1lIjoiIiwibGFzdF9uYW1lIjoiIiwiaXNfc3RhZmYiOnRydWUsImlzX2FjdGl2ZSI6dHJ1ZSwiZGF0ZV9qb2luZWQiOiIyMDIyLTEyLTE0VDExOjA3OjM2LjEyODg0OVoiLCJlbWFpbCI6IiIsInBob3RvIjpudWxsLCJsYW5ndWFnZSI6ImVuLVVTIiwicGluQ29kZSI6bnVsbCwiZ3JvdXBzIjpbXSwidXNlcl9wZXJtaXNzaW9ucyI6W119LCJkYXRhYmFzZSI6ImRlZmF1bHQiLCJleHAiOjE2NzEwMjA1NjR9.qlVlKuuwUS-EOIM1uyjT5fQOoaTGU9fNlkN0l80zqdc




### Refresh Tokens
POST http://localhost:8000/auth/refresh/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoxLCJsYXN0X2xvZ2luIjpudWxsLCJpc19zdXBlcnVzZXIiOnRydWUsInVzZXJuYW1lIjoiYWJiYXMiLCJmaXJzdF9uYW1lIjoiIiwibGFzdF9uYW1lIjoiIiwiaXNfc3RhZmYiOnRydWUsImlzX2FjdGl2ZSI6dHJ1ZSwiZGF0ZV9qb2luZWQiOiIyMDIyLTEyLTE0VDExOjA3OjM2LjEyODg0OVoiLCJlbWFpbCI6IiIsInBob3RvIjpudWxsLCJsYW5ndWFnZSI6ImVuLVVTIiwicGluQ29kZSI6bnVsbCwiZ3JvdXBzIjpbXSwidXNlcl9wZXJtaXNzaW9ucyI6W119LCJkYXRhYmFzZSI6ImRlZmF1bHQiLCJleHAiOjE2NzEwNjI3MTR9.wlZshAEXnYPOZGGlW_FrSKKk6A_V-dq81jgHQtm7cFY




