### Login User
POST http://localhost:8000/auth/login/
Content-Type: application/json

{
  "username": "abbas",
  "password": "abbas",
  "company": "default"
}

### Login User 2
POST http://localhost:8000/auth/login/
Content-Type: application/json

{
  "username": "abbas",
  "password": "abbas",
  "company": "company1"
}


### Refresh Tokens
POST http://localhost:8000/auth/refresh/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7ImlkIjoxLCJsYXN0X2xvZ2luIjoiMjAyMi0xMi0xMVQxMjoxNzoxOC4zNTcwNjVaIiwiaXNfc3VwZXJ1c2VyIjp0cnVlLCJ1c2VybmFtZSI6ImFiYmFzIiwiZmlyc3RfbmFtZSI6IiIsImxhc3RfbmFtZSI6IiIsImlzX3N0YWZmIjp0cnVlLCJpc19hY3RpdmUiOnRydWUsImRhdGVfam9pbmVkIjoiMjAyMi0xMi0xMVQxMjoxNzowMy45NTMyOTZaIiwiZW1haWwiOiJhYmJhcy5tai5zcm91ckBnbWFpbC5jb20iLCJwaG90byI6bnVsbCwibGFuZ3VhZ2UiOiJlbi1VUyIsInBpbkNvZGUiOm51bGwsImdyb3VwcyI6W10sInVzZXJfcGVybWlzc2lvbnMiOltdfSwiZGF0YWJhc2UiOiJkZWZhdWx0IiwiZXhwIjoxNjcxMDE4NzY4fQ.u3slB1cTPE0FUo5jp7eYru_A5_efERxmtZJ8R92O9Kk